[WIP] Hiding dependency on ZeroMQ from public headers
jupyter-xeus/xeus-zmq pull request #33
Opened 2024-02-02 08:09 UTC by anutosh491

2024-02-06 12:50 UTC, anutosh491 commented
Still need to update some directories like the test directory.

2024-02-07 08:31 UTC, JohanMabille requested changes

2024-02-07 08:31 UTC, JohanMabille commented on include/xeus-zmq/xserver_zmq.hpp
> +        ~xserver_zmq();
```suggestion
        ~xserver_zmq() override;
```

2024-02-07 08:31 UTC, JohanMabille commented on include/xeus-zmq/xserver_zmq.hpp
>          void update_config_impl(xconfiguration& config) const override;
These methods can no be private

2024-02-07 08:31 UTC, JohanMabille commented on include/xeus-zmq/xserver_zmq.hpp
>      class XEUS_ZMQ_API xserver_zmq : public xserver
`xserver_zmq` should be final now.

2024-02-07 08:31 UTC, JohanMabille commented on include/xeus-zmq/xserver_zmq.hpp
> +        xserver_zmq_impl* p_impl;
Storing a `std::unique_ptr<xserver_zmq_impl>` instead of a raw pointer would allow to use the default destructor.

2024-02-07 08:33 UTC, JohanMabille commented
You can also remove the macro `XEUS_ZMQ_API` from the classes that have been moved to the `src` folder.

2024-02-07 13:02 UTC, JohanMabille commented on src/xserver_zmq.cpp
> -    xserver_zmq::~xserver_zmq() = default;
You need to keep this in the cpp, otherwise you get either a missing symbol (even a missing vtable in our case), or a crash if it builds.

2024-02-09 09:40 UTC, JohanMabille approved these changes

2024-02-09 10:34 UTC, merged

2024-02-09 10:34 UTC, anutosh491 commented
Thanks for the reviews on this !